_target_: src.modules.sv.SpeakerVerification

defaults:
  - _self_

model:
  audio_processor: ???
  audio_processor_normalizer: ???
  audio_encoder: ???
  classifier: ???

### criteria and metrics ###
criterion:
  aam:
    _target_: speechbrain.nnet.losses.LogSoftmaxWrapper
    loss_fn:
      _target_: speechbrain.nnet.losses.AdditiveAngularMargin
      margin: 0.2
      scale: 30.0
  train_criterion: ${module.criterion.aam}
  valid_criterion: ${module.criterion.aam}

  # For callbacks
  loss: ${module.criterion.train_criterion}

metrics:
  train:
    _target_: "torchmetrics.Accuracy"
    task: "multiclass"
    num_classes: ${datamodule.num_classes}
  valid:
    _target_: "torchmetrics.Accuracy"
    task: "multiclass"
    num_classes: ${datamodule.num_classes}
  valid_best:
    _target_: torchmetrics.MaxMetric
  test:
    _target_: src.modules.metrics.metrics.VerificationMetrics

### optimizer and lr_scheduler ###
optimizer: ???
lr_scheduler: ???

### extras and callbacks ###
logging_params:
  on_step: False
  on_epoch: True
  sync_dist: True
  prog_bar: True

### scoring pipeline ###
scoring:
  enrollment_aggregation: mean # "mean" or "length_weighted"
  mean_source: cohort # "cohort" or "none"
  norm_method: as_norm # "as_norm" or "none"
  cohort:
    speaker_level: true
    topk_speakers: 300
