# https://neptune.ai

neptune:
  _target_: pytorch_lightning.loggers.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  project: 'ahmad.aloradi94/vpc25'
  log_model_checkpoints: False
  with_id: ${oc.env:NEPTUNE_RUN_ID,null}  # Set to run_id when continuing
  name: null
  mode: "async"