_target_: src.datamodules.vpc_datamodule.AnonymizedLibriSpeechDataModule

root_dir: ${paths.data_dir}/vpc2025_official

splits:
  train: train-clean-360
  valid: libri_dev_enrolls
  test: libri_test_trials_f

subset_dirs: 
  - ${datamodule.root_dir}/B3
  - ${datamodule.root_dir}/B5
  - ${datamodule.root_dir}/T12-5

transform: null

loaders:
  train:
    batch_size: 8
    shuffle: True
    num_workers: 4
    drop_last: True
    pin_memory: False

  valid:
    batch_size: 8
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False

  test:
    batch_size: 8
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False

  predict:
    batch_size: 8
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False
